### ISSUE TITLE
You shouldn't push `speech2text-3de4444fd46a.json` to GitHub.

### ISSUE THREAD

**Issue by annieFromTaiwan** [HowardNTUST/Marketing-Data-Science-Application#2]
The content in this json file is like your credit card number. You shouldn't publish these information onto GitHub. People can then use the private key in this file to perform Google API, and that would cost you money. (From what I know, Google API is not free.)

Now that this key is being published. I guess what you can do is to go to Google Console and invalidate this private key.

https://github.com/HowardNTUST/Marketing-Data-Science-Application/blob/2a0743eb6a83d805af7d3dd9ab7f26ce4c88e0ae/speech2text_1min/speech2text-3de4444fd46a.json#L1

**Comment by HowardNTUST** [comment]
@annieFromTaiwan  Thank you for informing me of this issue! your reminder is highly appreciated ! 
Actually, I've known that the use of private json key might compromise my account credits or money to be said, however, I was granted US$250 more free credits in this account that I'd like to share with those interested in trying these python codes given. When credits are consumed to $0, the account I set will automatically be closed leading to no cost of  my real credits.

**Comment by annieFromTaiwan** [comment]
Wow! You're very generous! 👍
